### ISSUE TITLE
Failing partialRefunds because of missing capture reference

### ISSUE THREAD

**Issue by LSshopmacher** [commercetools/commercetools-adyen-integration#975]
Some of our refunds are not working in Adyen, the support told us this:
![image](https://user-images.githubusercontent.com/93180076/173850388-a8780b58-9b36-46ae-8a1f-9b969e764275.png)
![image](https://user-images.githubusercontent.com/93180076/173851070-a4cfa99f-c4df-47dc-9336-cb9c2ab96df1.png)

> Do note that multiple partial capture and refunds require extra attention because the PayPal API requires us to link each refund to one single capture. It is very important for merchants to build logic on their end to match each refund to a captures using the reference (so the reference of the refund matches 1:1 to the reference of the capture to be used). When considering multiple partial capture, take into account that:
> 
> ·         The max amount per refund is equal to the amount of the largest capture (assuming nothing has yet been refunded on that capture).
> 
> ·         If refunds do not exactly match captures, it will most likely result in certain amounts being 'unrefundable' through Adyen because we cannot find a capture with enough balance while the payment still has enough balance.
> 
> ·         When you supply a reference in your refund requests, it must match the reference of a capture.
> 
> ·         If the merchant does not supply a reference, we will automatically look for the best fitting capture but this is a brittle process which has regular failures and we can not guarantee the modification will go through successfully.
> 
>  
> In the case of the affected transactions, as there is no capture reference being sent, I would advise you to refund it outside of our platform or through an alternative payment method. 

As we are using an unmodified version of the CT/Adyen Extension I think it's a bug?

**Comment by lojzatran** [comment]
Hi @LSshopmacher 

Thank you for submitting the issue. 

I had a look at the problem and also at [the Adyen documentation](https://docs.adyen.com/online-payments/refund) that we are following and I could not find what was recommended to you by Adyen support. I will further clarify this with Adyen support.

Can you tell us what payment method are you trying to refund here?

Thank you.

**Comment by LSshopmacher** [comment]
Thank you for your help. PayPal was the payment method.

**Comment by lojzatran** [comment]
Thank you for the reply.

For now I cannot say if we need to fix sth or not, because what you wrote is not documented. I will reply to you once we got a confirmation from Adyen with detailed instruction how to do it.

**Comment by lojzatran** [comment]
Hi @LSshopmacher 

I clarified with Adyen and it is like you wrote. When doing partial capture and then partial refund, these refunds needs to be linked in the captures via the `reference` field. I had a look [in our code](https://github.com/commercetools/commercetools-adyen-integration/blob/7406b24804311aa3d736174d2d343cd0e6621cd2/extension/src/paymentHandler/refund-payment.handler.js#L31) and we are not doing that, so it is a bug.

I created a JIRA ticket for it. As the next step we will need to check how to address this issue and discuss in the team. I will inform you once we proceed further. Thank you.

**Comment by TimWieseSport2000** [comment]
Hi @lojzatran 

please tell me more about the current stand of this issue. 
We are currently seeing a growing number of orders in our project and we have to solve this issue asap. 
Thank you!

**Comment by lojzatran** [comment]
Hi @TimWieseSport2000 

Sorry for the delay on this issue. We tested it and we could not reproduce the issue with the payment methods we currently have. It seems like the issue happens only for paypal and for this method we do not have tests to reproduce. Also Adyen could not confirm nor reject this issue as sth that happens only in paypal.

For now we could propose the following solution: you (the shop) could be able to add this reference as a custom field when creating refund. It could work as follow:
1. When [adding the refund transaction](https://github.com/commercetools/commercetools-adyen-integration/blob/master/extension/docs/Refund.md#steps), there will be an option to add a [custom field](https://docs.commercetools.com/api/projects/payments#transactiondraft) to the refund transaction. This field could be called `reference`.
1. If the field `reference` is added, adyen-integration will use this field. If not, it will use the default behaviour, which is the [payment object key](https://github.com/commercetools/commercetools-adyen-integration/blob/7406b24804311aa3d736174d2d343cd0e6621cd2/extension/src/paymentHandler/refund-payment.handler.js#L31).

This means you have to set take care of setting `reference` field so it matches the correct Capture.

Does this solution work for you?

**Comment by LSshopmacher** [comment]
Hi @lojzatran 
that means, that every CT that is using Adyen and PayPal has to add this custom field to have partial refunds working correctly.
Please add this to the docs, we are going to add it in our CT and refund process. I am going to tell you in a few days if it worked or not.
Thank you
Lennart

**Comment by lojzatran** [comment]
Hi @LSshopmacher 

That is correct.

This function is planned to be implemented and released within next week, so you cannot test it yet. I will let you know once it is released.

Thank you.

**Comment by lojzatran** [comment]
Hi @LSshopmacher 

I released a new version with the change above. https://github.com/commercetools/commercetools-adyen-integration/releases/tag/v9.10.0

It should fix your problem in this issue. Therefore I'm closing it. Let me know if you have further questions.

Thank you.

**Comment by LSshopmacher** [comment]
@lojzatran we updated the extension and added the reference field during the refund request.

`{
   "modificationAmount" : {
      "value" : 5499,
      "currency" : "EUR"
   },
   "originalReference" : "ssdfsdfsdf2423232sdsdsd",
   "reference" : "631354343433d9-53048641",
   "metadata" : {
      "ctProjectKey" : "my-prod"
   },
   "merchantAccount" : "my2000_de"
}`

But it is still not working, I asked the Adyen support why, they told us:

> You're probably trying to match the capture from 02-09. However, multiple partial capture + refunds are tricky on PayPal because the PayPal API requires us to link each refund to one single capture. You must make sure to build the logic on your end to match each refund to a capture using the reference (so the reference of the refund matches 1:1 to the reference of the capture to be used). When considering multiple partial capture, take into account that:
> - The max amount per refund is equal to the amount of the largest capture (assuming nothing has yet been refunded on that capture).
> - If refunds do not exactly match captures, it will most likely result in certain amounts being 'unrefundable' through Adyen because we cannot find a capture with enough balance while the payment still has enough balance.
> - If you supply a reference in the refund request, it must match the reference of a capture
> - If you do not supply a reference, we will automatically look for the best fitting capture but this is a brittle process which has regular failures, which is what happened in this case because the capture had no reference. 
>  
> Do let me know if you need more information.

As you can see in my initial screenshot, the CAPTURE request has no unique reference. Adyen says this is the capture request the extension is sending:

`{
   "modificationAmount" : {
      "value" : 5499,
      "currency" : "EUR"
   },
   "originalReference" : "fsdfsdfsdf3434734hdfdf",
   "metadata" : {
      "ctProjectKey" : "my-prod"
   },
   "merchantAccount" : "my2000_de"
}`

I guess we have to add a unique reference field to the CAPTURE and the same reference to the REFUND...

![image](https://user-images.githubusercontent.com/93180076/189891781-b0db11fc-ede7-4882-9d0a-79619c70ce10.png)

**Comment by lojzatran** [comment]
Hi @LSshopmacher 

Thank you for informing us. I guess you need to supply the reference for Capture as well? We recently added this feature, please have a look if this is what you need: https://github.com/commercetools/commercetools-adyen-integration/releases/tag/v9.12.0

**Comment by LSshopmacher** [comment]
As far as I can see, https://github.com/commercetools/commercetools-adyen-integration/releases/tag/v9.13.0 is even better, because it's now setting this reference on it's own...

I will try that version.
